spring:
  datasource:
    url: jdbc:h2:file:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All Tasks
    database:
      type: h2 